function normalize(value=""){return value.toLocaleLowerCase("fr").normalize("NFD").replace(/\p{Diacritic}/gu,"")}
function hash(input){let h=2166136261;for(const c of input){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
export function scoreDreamCultureCard(card,input,journey={},randomFactor=0){const terms=[...input.tags,input.customTag||"",input.message||""].map(normalize);const matchingTags=card.tags.filter(t=>terms.some(x=>x.includes(normalize(t))||normalize(t).includes(x))).length;const matchingEmojis=card.emojis.filter(e=>input.emojis.includes(e)).length;const matchingSymbols=card.symbols.filter(s=>terms.some(x=>x.includes(normalize(s)))).length;const categoryDiversityBonus=journey.lastCategory&&journey.lastCategory!==card.category?2:0;const discoveryBonus=(journey.discoveredRegions||[]).includes(card.region)?0:4;const cultureBonus=(journey.discoveredCultures||[]).includes(card.culture)?0:5;return matchingTags*5+matchingEmojis*3+matchingSymbols*2+categoryDiversityBonus+discoveryBonus+cultureBonus+card.weight+randomFactor}
export function selectDreamCultureCard(input,journey={},cards){const recent=new Set((journey.recentCardIds||[]).slice(-5));const candidates=cards.filter(c=>!recent.has(c.id));const stable=JSON.stringify({e:[...input.emojis].sort(),t:[...input.tags].sort(),c:input.customTag||"",m:input.message||"",n:journey.scanCount||0});return (candidates.length?candidates:cards).map(card=>({card,score:scoreDreamCultureCard(card,input,journey,(hash(stable+card.id)%100)/1000)})).sort((a,b)=>b.score-a.score||a.card.id.localeCompare(b.card.id))[0].card}

// L'ordre des trois signes fait partie du choix : un signe placé en premier
// résonne un peu plus fortement que le troisième, sans prétendre l'interpréter.
export function selectWorldDreamResource(emojis,cards){
 if(!Array.isArray(emojis)||emojis.length!==3)throw new Error("Trois emojis sont requis.");
 const sequence=emojis.join("|");
 return cards.map(card=>{const positions=card.emojis.map(emoji=>emojis.indexOf(emoji)).filter(index=>index>=0);const matches=positions.length;const orderWeight=positions.reduce((score,index)=>score+(3-index),0);const adjacent=emojis.some((emoji,index)=>card.emojis.includes(emoji)&&card.emojis.includes(emojis[index+1]))?2:0;return{card,score:matches*10+orderWeight+adjacent+card.weight+(hash(`${sequence}:${card.id}`)%100)/1000}}).sort((a,b)=>b.score-a.score||a.card.id.localeCompare(b.card.id))[0].card;
}
