import {useMemo,useState} from "react";
import {fillProjectiveDream} from "../../lib/projectiveDreamEngine";
type Gap={prompt:string;choices:[string,string,string]};
type Dream={id:string;title:string;seed:string;emojiSequence:string[];parts:string[];gaps:Gap[]};
type Props={dream:Dream;onRelease:(text:string,answers:string[])=>void};
export default function DreamReading({dream,onRelease}:Props){
 const[answers,setAnswers]=useState(()=>dream.gaps.map(()=>"")),[custom,setCustom]=useState(()=>dream.gaps.map(()=>false));
 const completed=answers.filter(answer=>answer.trim()).length,preview=useMemo(()=>fillProjectiveDream(dream,answers),[dream,answers]);
 const choose=(index:number,value:string)=>{setAnswers(current=>current.map((answer,i)=>i===index?value:answer));setCustom(current=>current.map((open,i)=>i===index?false:open))};
 const chooseOther=(index:number)=>{setAnswers(current=>current.map((answer,i)=>i===index?"":answer));setCustom(current=>current.map((open,i)=>i===index?true:open))};
 const update=(index:number,value:string)=>setAnswers(current=>current.map((answer,i)=>i===index?value:answer));
 return <main className="reading-screen projective-dream"><header className="projective-heading"><p className="ocean-whisper">UN RÊVE À COMPLÉTER</p><span aria-hidden="true">{dream.emojiSequence.join(" · ")}</span><h1>{dream.title}</h1><p>Choisis ce qui apparaît. Ou laisse venir autre chose.</p></header><article className="dream-with-gaps" aria-label="Rêve projectif à compléter">{dream.parts.map((part,index)=><span className="dream-part" key={index}>{part}{index<dream.gaps.length&&<span className="gap-composer"><span className="gap-prompt">{dream.gaps[index].prompt}</span><span className="gap-options" role="group" aria-label={`Choisis ${dream.gaps[index].prompt}`}>{dream.gaps[index].choices.map(choice=><button type="button" key={choice} aria-pressed={!custom[index]&&answers[index]===choice} onClick={()=>choose(index,choice)}>{choice}</button>)}<button type="button" className="other-choice" aria-pressed={custom[index]} onClick={()=>chooseOther(index)}>Autre…</button></span>{custom[index]&&<label className="custom-dream-answer"><span>Ta propre apparition</span><textarea autoFocus rows={1} maxLength={90} value={answers[index]} onChange={event=>update(index,event.target.value)} placeholder="Écris ce qui te vient…"/></label>}</span>}</span>)}</article><p className="completion-whisper" aria-live="polite">{completed===0?"Tu peux aussi laisser des espaces silencieux.":completed===dream.gaps.length?"Ton rêve est complet.":`${completed} apparition${completed>1?"s":""} sur ${dream.gaps.length}.`}</p><details className="dream-preview"><summary>Relire le rêve d’un seul souffle</summary><p>{preview}</p></details><button className="release-dream completed-dream-action" onClick={()=>onRelease(preview,answers)}>Garder ce rêve et passer la noix <span>○</span></button></main>
}
