import {useEffect,useState} from "react";
import type {DreamBubble as DreamBubbleType} from "../../dream-engine/types/dream";
import DreamBubble from "./DreamBubble";
import ResonancePicker from "./ResonancePicker";
type Props={bubble:DreamBubbleType;initialRevealed?:number;onProgress:(count:number)=>void;onResonance:(type:string,word:string)=>void;onRelease:()=>void};
function plopSound(){const Audio=window.AudioContext||(window as typeof window&{webkitAudioContext:typeof AudioContext}).webkitAudioContext;if(!Audio)return;const ctx=new Audio(),osc=ctx.createOscillator(),gain=ctx.createGain(),filter=ctx.createBiquadFilter();osc.type="sine";osc.frequency.setValueAtTime(185+Math.random()*22,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(92,ctx.currentTime+.11);filter.type="lowpass";filter.frequency.value=520;gain.gain.setValueAtTime(.0001,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.055,ctx.currentTime+.012);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.13);osc.connect(filter).connect(gain).connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.14);osc.onended=()=>ctx.close()}
export default function DreamBubbleExplorer({bubble,initialRevealed=0,onProgress,onResonance,onRelease}:Props){const[revealed,setRevealed]=useState(Math.min(initialRevealed,bubble.fragments.length)),[sound,setSound]=useState(false),[plop,setPlop]=useState<{x:number;y:number;key:number}|null>(null),[resonance,setResonance]=useState(""),[word,setWord]=useState(""),complete=revealed===bubble.fragments.length;
 useEffect(()=>{onProgress(revealed)},[revealed,onProgress]);
 const reveal=(event:React.MouseEvent<HTMLButtonElement>)=>{if(complete)return;const rect=event.currentTarget.getBoundingClientRect();setPlop({x:event.clientX-rect.left,y:event.clientY-rect.top,key:Date.now()});setTimeout(()=>setPlop(null),500);if(sound)plopSound();setRevealed(value=>value+1)};
 const hint=revealed===3?"Continue à faire éclater les résonances.":revealed===bubble.fragments.length-1?"Il reste quelque chose dans la bulle.":complete?"La bulle est ouverte.":"Touche la bulle.";
 return <main className="bubble-explorer"><header><p>UNE BULLE ONIRIQUE</p><button className="sound-toggle" onClick={()=>setSound(value=>!value)} aria-label={`Son ${sound?"activé":"désactivé"}`}>{sound?"Son · oui":"Son · non"}</button></header><section className="plop-stage"><button className="plop-bubble" onClick={reveal} disabled={complete} aria-label={complete?"Tous les fragments sont apparus":"Faire éclater une résonance"} style={{"--remaining":`${1-revealed/bubble.fragments.length*.24}`} as React.CSSProperties}><DreamBubble size="large" intensity={Math.max(.18,1-revealed/bubble.fragments.length*.65)}/>{plop&&<i className="plop-word" style={{left:plop.x,top:plop.y}}>PLOP</i>}</button><p className="progress-hint">{hint}</p><div className="bubble-dots" aria-label={`${bubble.fragments.length-revealed} fragments restent à révéler`}>{bubble.fragments.map((fragment,index)=><i className={index<revealed?"open":""} key={fragment.id}/>)}</div></section><p className="sr-live" aria-live="polite">{revealed?bubble.fragments[revealed-1].text:""}</p><ol className="fragment-field">{bubble.fragments.slice(0,revealed).map((fragment,index)=><li className={`fragment-${bubble.alignments[index]||"left"}`} key={fragment.id}>{fragment.text}</li>)}</ol>{complete&&<ResonancePicker value={resonance} word={word} onWordChange={value=>{setWord(value);onResonance(resonance,value)}} onChange={value=>{setResonance(value);onResonance(value,word)}} onRelease={onRelease}/>}</main>}
