import {useEffect,useMemo,useRef,useState} from "react";
import {EMOJIS} from "../../data/dreamCultures";
import {generateProjectiveDream} from "../../lib/projectiveDreamEngine";
import {saveLocalDream} from "../../services/dreamSyncService";
import TestEnvironmentPanel from "../TestEnvironmentPanel";
import Dreamcatcher from "./Dreamcatcher";
import DreamReading from "./DreamReading";
import DreamWeaving from "./DreamWeaving";
import GrandOBackground from "./GrandOBackground";
import NaoBoat from "./NaoBoat";
import NaoLogo from "./NaoLogo";
import "../../styles/nao.css";
type Phase="entry"|"choosing"|"weaving"|"reading"|"released";type Props={onLeave?:()=>void};
export default function NaoOdyssey({onLeave}:Props){const[phase,setPhase]=useState<Phase>("entry"),[selected,setSelected]=useState<string[]>([]),[departing,setDeparting]=useState(false),saving=useRef(false),dream=useMemo(()=>selected.length===3?generateProjectiveDream(selected):null,[selected]);const toggle=(emoji:string)=>setSelected(current=>current.includes(emoji)?current.filter(item=>item!==emoji):current.length<3?[...current,emoji]:current);
 useEffect(()=>{if(selected.length!==3||phase!=="choosing")return;const id=setTimeout(()=>setPhase("weaving"),500);return()=>clearTimeout(id)},[selected,phase]);
 useEffect(()=>{if(phase!=="weaving")return;const id=setTimeout(()=>setPhase("reading"),1800);return()=>clearTimeout(id)},[phase]);
 const release=async(dreamText:string,answers:string[])=>{if(!dream||saving.current)return;saving.current=true;await saveLocalDream({title:dream.title,dreamText,cultureIds:[],emojiSequence:selected,projectiveAnswers:answers,seed:dream.seed}).catch(()=>{});setDeparting(true);setTimeout(()=>setPhase("released"),700)};let content;
 if(phase==="entry")content=<main className="grand-o-entry"><NaoLogo/><div className="odyssey-intro"><div className="boat-horizon"><NaoBoat size="hero"/></div><h1>L’Odyssée de Nao Dream</h1><p className="odyssey-subtitle">La petite noix qui voyage de main en main pour réveiller les rêves du monde <span>•°</span></p><div className="odyssey-story"><p>Choisis trois emojis. Leur séquence fera apparaître un rêve à trous.</p><p className="odyssey-closing">Quelques mots manquent. Ton imaginaire sait peut-être où les trouver.</p></div><button className="enter-ocean" onClick={()=>setPhase("choosing")}><span>Entrer dans le Grand O•°</span><i/></button></div><details className="system-tide"><summary>État du courant</summary><TestEnvironmentPanel/></details>{onLeave&&<button className="leave-ocean" onClick={onLeave}>Explorer autrement</button>}</main>;
 else if(phase==="choosing")content=<Dreamcatcher emojis={EMOJIS} selected={selected} onToggle={toggle} onBack={()=>{setSelected([]);setPhase("entry")}}/>;
 else if(phase==="weaving")content=<DreamWeaving/>;
 else if(phase==="reading"&&dream)content=<div className={departing?"dream-departing":""}><DreamReading dream={dream} onRelease={release}/></div>;
 else content=<main className="released-screen"><div className="released-bubble">○</div><NaoBoat size="medium" motion="depart"/><p>Ton rêve peut maintenant poursuivre son voyage.</p><button onClick={()=>{saving.current=false;setSelected([]);setPhase("entry")}}>Passer la noix</button></main>;
 return <div className={`nao-odyssey phase-${phase}`}><GrandOBackground/>{content}</div>}
