import {useCallback,useEffect,useRef,useState} from "react";
import {DREAM_EMOJIS,generateDreamBubble} from "../../dream-engine/engine/generateDreamBubble";
import {clearDreamSession,makeStoredBubble,readDreamHistory,rememberDreamFragments,restoreDreamSession,saveDreamSession} from "../../dream-engine/engine/dreamSession";
import type {DreamBubble as DreamBubbleType,StoredDreamBubble} from "../../dream-engine/types/dream";
import {saveLocalDream,syncPendingDreams} from "../../services/dreamSyncService";
import {dreamDraftStore} from "../../stores/useDreamDraftStore";
import TestEnvironmentPanel from "../TestEnvironmentPanel";
import DreamBubbleExplorer from "./DreamBubbleExplorer";
import Dreamcatcher from "./Dreamcatcher";
import DreamWeaving from "./DreamWeaving";
import GrandOBackground from "./GrandOBackground";
import NaoBoat from "./NaoBoat";
import NaoLogo from "./NaoLogo";
import "../../styles/nao.css";
type Sign={id:string;emoji:string;label:string}; type Phase="entry"|"choosing"|"weaving"|"exploring"|"released"; type Props={onLeave?:()=>void};
const sessionId=()=>{const key="nao-dream-session-id";let id=sessionStorage.getItem(key);if(!id){id=crypto.randomUUID();sessionStorage.setItem(key,id)}return id};
export default function NaoOdyssey({onLeave}:Props){const restoredRef=useRef<StoredDreamBubble|null>(restoreDreamSession()),[phase,setPhase]=useState<Phase>(restoredRef.current?.releasedAt?"released":restoredRef.current?"exploring":"entry"),[selected,setSelected]=useState<Sign[]>(()=>restoredRef.current?restoredRef.current.emojiIds.map(id=>DREAM_EMOJIS.find(sign=>sign.id===id)!).filter(Boolean):[]),[stored,setStored]=useState<StoredDreamBubble|null>(restoredRef.current),[bubble,setBubble]=useState<DreamBubbleType|null>(()=>restoredRef.current?generateDreamBubble({emojiIds:restoredRef.current.emojiIds,seed:restoredRef.current.seed,patternId:restoredRef.current.patternId,createdAt:restoredRef.current.createdAt}):null),saved=useRef(Boolean(restoredRef.current));
 const toggle=(sign:Sign)=>setSelected(current=>current.some(item=>item.id===sign.id)?current.filter(item=>item.id!==sign.id):current.length<3?[...current,sign]:current);
 const move=(from:number,to:number)=>setSelected(current=>{const next=[...current],[item]=next.splice(from,1);next.splice(to,0,item);return next});
 const create=()=>{if(selected.length!==3)return;const now=new Date(),bucket=Math.floor(now.getTime()/300000),seed=`NAO-DREAM-001:${sessionId()}:${selected.map(item=>item.id).join("|")}:${bucket}`,created=generateDreamBubble({emojiIds:selected.map(item=>item.id),seed,history:readDreamHistory(),locale:"fr",createdAt:now.toISOString()}),record=makeStoredBubble(created,sessionId());setBubble(created);setStored(record);saveDreamSession(record);setPhase("weaving")};
 useEffect(()=>{if(phase!=="weaving")return;const id=setTimeout(()=>setPhase("exploring"),1800);return()=>clearTimeout(id)},[phase]);
 useEffect(()=>{if(!bubble||!stored||saved.current)return;saved.current=true;rememberDreamFragments(bubble.fragmentIds);saveLocalDream({...stored,title:"Bulle onirique",dreamText:bubble.fragments.map(fragment=>fragment.text).join("\n"),cultureIds:[],libraryVersion:bubble.libraryVersion}).catch(()=>{})},[bubble,stored]);
 const progress=useCallback((revealedCount:number)=>setStored(current=>{if(!current||current.revealedCount===revealedCount)return current;const next={...current,revealedCount,...(revealedCount===current.fragmentIds.length?{completedAt:new Date().toISOString()}: {})};saveDreamSession(next);dreamDraftStore.updateDream(next.id,next);return next}),[]);
 const resonate=useCallback((resonanceType:string,resonanceWord:string)=>setStored(current=>{if(!current)return current;const next={...current,resonanceType,resonanceWord:resonanceWord||undefined};saveDreamSession(next);dreamDraftStore.updateDream(next.id,next);return next}),[]);
 const release=()=>{setStored(current=>{if(!current)return current;const next={...current,releasedAt:new Date().toISOString()};saveDreamSession(next);dreamDraftStore.updateDream(next.id,next);dreamDraftStore.markPending(next.id);return next});syncPendingDreams().catch(()=>{});setPhase("released")};
 const restart=()=>{clearDreamSession();saved.current=false;setStored(null);setBubble(null);setSelected([]);setPhase("entry")};
 let content;if(phase==="entry")content=<main className="grand-o-entry"><NaoLogo/><div className="odyssey-intro"><div className="boat-horizon"><NaoBoat size="hero"/></div><h1>L’Odyssée de Nao Dream</h1><p className="odyssey-subtitle">La petite noix qui voyage de main en main pour réveiller les rêves du monde <span>•°</span></p><div className="odyssey-story"><p>Trois signes se rapprochent. Une bulle onirique apparaît, fragment après fragment.</p><p className="odyssey-closing">Les rêves ne s’interprètent pas. Ils résonnent.</p></div><button className="enter-ocean" onClick={()=>setPhase("choosing")}><span>Entrer dans le Grand O•°</span><i/></button></div><details className="system-tide"><summary>État du courant</summary><TestEnvironmentPanel/></details>{onLeave&&<button className="leave-ocean" onClick={onLeave}>Explorer autrement</button>}</main>;
 else if(phase==="choosing")content=<Dreamcatcher signs={DREAM_EMOJIS} selected={selected} onToggle={toggle} onMove={move} onCreate={create} onBack={()=>{setSelected([]);setPhase("entry")}}/>;
 else if(phase==="weaving")content=<DreamWeaving/>;
 else if(phase==="exploring"&&bubble)content=<DreamBubbleExplorer bubble={bubble} initialRevealed={stored?.revealedCount} onProgress={progress} onResonance={resonate} onRelease={release}/>;
 else content=<main className="released-screen"><div className="released-bubble">○</div><NaoBoat size="medium" motion="depart"/><p>Un rêve du monde vient de rejoindre le Grand O•°.</p><small>Nao peut maintenant poursuivre son voyage.</small><button onClick={restart}>Passer la noix</button></main>;
 return <div className={`nao-odyssey phase-${phase}`}><GrandOBackground/>{content}</div>}
