import { useState } from "react";
import Layout from "../components/Layout";
import HomePage from "../pages/HomePage"; import RitualPage from "../pages/RitualPage"; import FingerprintPage from "../pages/FingerprintPage"; import EchoPage from "../pages/EchoPage"; import ResonancePage from "../pages/ResonancePage"; import PassPage from "../pages/PassPage";
import { useNaoStore } from "../store/useNaoStore"; import { getNetworkEcho } from "../services/echoService"; import { generateResonance } from "../services/resonanceService"; import { consumeCredit, getCreditBalance, packs, purchaseCreditPack } from "../services/creditService"; import { prepareNextPass } from "../services/naoPassService";
export default function App() { const store = useNaoStore(); const [screen, setScreen] = useState("home"); const [credits, setCredits] = useState(getCreditBalance); const [localOnly, setLocalOnly] = useState(false); const [showPacks, setShowPacks] = useState(false); const [passChoice, setPassChoice] = useState("");
 const update = (key, value) => store.setFingerprint((current) => ({ ...current, [key]: value }));
 const send = async () => { const fingerprint = store.finalizeFingerprint(); setScreen("compost"); const echo = await getNetworkEcho(fingerprint); setTimeout(() => { store.setEcho(echo); setScreen("echo"); }, 1700); };
 const reveal = async () => { if (!consumeCredit()) return setShowPacks(true); setCredits(getCreditBalance()); store.setResonance(await generateResonance(store.fingerprint)); setScreen("resonance"); };
 const buy = (id) => { setCredits(purchaseCreditPack(id)); setShowPacks(false); };
 let page; if (screen === "home") page = <HomePage next={() => setScreen("ritual")} howItWorks={() => setScreen("ritual")}/>; else if (screen === "ritual") page = <RitualPage next={() => setScreen("emotions")}/>; else if (["emotions", "themes", "movement", "privacy"].includes(screen)) page = <FingerprintPage stage={screen} fingerprint={store.fingerprint} update={update} next={() => screen === "emotions" ? setScreen("themes") : screen === "themes" ? setScreen("movement") : screen === "movement" ? setScreen("privacy") : send()}/>; else if (screen === "compost") page = <section className="page compost-page"><div className="compost-orb">•°</div><h2 className="page-title">NAO composte ton souci…</h2><p className="page-text">Une onde cherche maintenant ses résonances dans le monde.</p></section>; else if (screen === "echo") page = <EchoPage echo={store.echo} reveal={reveal}/>; else if (screen === "resonance") page = <ResonancePage resonance={store.resonance} next={() => setScreen("pass")}/>; else page = <PassPage preparing={!passChoice || screen === "pass"} selected={passChoice} setSelected={setPassChoice} prepare={async () => { await prepareNextPass(); setScreen("finished"); }} done={() => { setPassChoice(""); store.setFingerprint({ emotions: [], themes: [], movement: "" }); setScreen("home"); }}/>;
 return <Layout credits={credits} localOnly={localOnly} toggleLocal={() => setLocalOnly(!localOnly)}>{page}{showPacks && <div className="modal-backdrop"><section className="purchase-modal"><button className="close" onClick={() => setShowPacks(false)}>×</button><p className="eyebrow">Résonance inspirante</p><h2>Il te faut un crédit.</h2><p>Pas d’abonnement : choisis simplement un pack.</p>{packs.map((pack) => <button className="pack" key={pack.id} onClick={() => buy(pack.id)}><b>{pack.credits} crédits</b><span>{pack.price}</span></button>)}</section></div>}</Layout>; }
