import { useEffect, useRef, useState } from "react";
import { DREAM_CARDS, EMOJIS, TAGS } from "../data/dreamCultures";
import { buildResonanceText } from "../lib/resonanceText";
import { selectDreamCultureCard } from "../lib/resonanceEngine";
import { createContribution, ensureDemoJourney, getSnapshot, unlockDiscovery } from "../lib/db";
import "../styles/global.css";

const NAO_ID = "NAO-DREAM-001";
const route = () => location.pathname;

function useRoute() {
  const [path, setPath] = useState(route);
  useEffect(() => { const onPop = () => setPath(route()); addEventListener("popstate", onPop); return () => removeEventListener("popstate", onPop); }, []);
  return [path, (next) => { history.pushState({}, "", next); setPath(next); scrollTo(0, 0); }];
}

function Shell({ path, go, children }) {
  return <div className="shell"><header><button className="brand" onClick={() => go("/")}><span className="nut">◉</span><span>NAO DREAM<small>La noix qui voyage</small></span></button><nav>{[[`/nao/${NAO_ID}`,"Scanner"],[`/nao/${NAO_ID}/journey`,"Voyage"],["/atlas","Atlas"],["/about","À propos"]].map(([to,label])=><button className={path.includes(to) ? "active":""} key={to} onClick={()=>go(to)}>{label}</button>)}</nav></header>{children}<footer>Une contribution courte · Une culture découverte · Une noix à transmettre</footer></div>;
}

function Home({ go, stats }) {
  return <main className="home"><div className="sky" aria-hidden="true"><i/><i/><i/><i/><span className="nao-boat">◒<b>✦</b></span></div><p className="kicker">UNE EXPÉRIENCE CULTURELLE EN 45 SECONDES</p><h1>NAO<br/><em>DREAM</em></h1><h2>La noix qui voyage dans les rêves du monde.</h2><p className="promise">Confie une étincelle de ton imaginaire à Nao. Elle cherchera ce qui lui répond dans les mythes, les traditions et les légendes oniriques du monde.</p><div className="hero-actions"><button className="primary" onClick={()=>go(`/nao/${NAO_ID}/resonance`)}>Faire résonner mon rêve <span>→</span></button><button className="ghost" onClick={()=>go(`/nao/${NAO_ID}/journey`)}>Voir le voyage de Nao</button></div><div className="stats"><span><b>{NAO_ID}</b>Noix</span><span><b>{stats?.journey?.scanCount || 5}</b>Passeurs</span><span><b>{stats?.journey?.discoveredCultures?.length || 5}</b>Cultures</span><span><b>{stats?.discoveries?.length || 5}</b>Cartes</span></div></main>;
}

function ResonanceForm({ onSubmit }) {
 const [emojis,setEmojis]=useState([]), [tags,setTags]=useState([]), [customTag,setCustomTag]=useState(""), [message,setMessage]=useState("");
 const toggle=(item,list,set,max)=>set(list.includes(item)?list.filter(x=>x!==item):list.length<max?[...list,item]:list);
 return <main className="form-page"><p className="step">01 · TON ÉTINCELLE</p><h1>Qu’est-ce qui traverse<br/>ton imaginaire aujourd’hui ?</h1><section><div className="label"><b>Choisis tes signes</b><span>1 à 3 emojis</span></div><div className="emoji-grid">{EMOJIS.map(e=><button aria-pressed={emojis.includes(e)} className={emojis.includes(e)?"selected":""} onClick={()=>toggle(e,emojis,setEmojis,3)} key={e}>{e}</button>)}</div></section><section><div className="label"><b>Pose quelques mots</b><span>1 à 3 thèmes</span></div><div className="tag-grid">{TAGS.map(t=><button aria-pressed={tags.includes(t)} className={tags.includes(t)?"selected":""} onClick={()=>toggle(t,tags,setTags,3)} key={t}>{t}</button>)}</div><input value={customTag} maxLength={24} onChange={e=>setCustomTag(e.target.value)} placeholder="Ton mot personnel (facultatif)"/></section><section><div className="label"><b>Quelques mots, si tu veux</b><span>{message.length}/120</span></div><textarea value={message} maxLength={120} onChange={e=>setMessage(e.target.value)} placeholder="Une image, un élan, une question…"/></section><button disabled={!emojis.length||!tags.length} className="primary" onClick={()=>onSubmit({emojis,tags,customTag:customTag.trim()||undefined,message:message.trim()||undefined})}>Chercher une résonance <span>✦</span></button><p className="privacy">Tout reste sur cet appareil. Aucune interprétation psychologique.</p></main>
}

function Transition({ input, done }) { const started=useRef(false),doneRef=useRef(done);doneRef.current=done;const finish=()=>{if(started.current)return;started.current=true;doneRef.current()};useEffect(()=>{const id=setTimeout(()=>{if(started.current)return;started.current=true;doneRef.current()},1900);return()=>clearTimeout(id)},[]); return <main className="transition"><div className="constellation">{input.emojis.map((e,i)=><span key={e} style={{"--i":i}}>{e}</span>)}<svg viewBox="0 0 300 100"><path d="M10 75 C70 0 160 110 290 20"/></svg></div><h1>Nao écoute ton imaginaire…</h1><p>Un rêve du monde lui répond.</p><button onClick={finish}>Passer</button></main> }

function CardArt({ card }) { return <div className={`card-art art-${card.category}`}><span>{card.emojis[0]}</span><div className="horizon"/><b>✦</b></div> }

function Discovery({ card, discovery, resonance, go, onUnlock }) {
 const [premium,setPremium]=useState(discovery?.premiumUnlocked), [modal,setModal]=useState(false), [shared,setShared]=useState("");
 const share=async()=>{const text=`${card.title} — ${card.culture}\n${resonance}\nDécouvert avec la noix Nao.`; try {if(navigator.share) await navigator.share({title:"Ma résonance Nao Dream",text}); else {await navigator.clipboard.writeText(text);setShared("Copié !")}}catch{setShared("Partage annulé")}};
 const open=async()=>{await onUnlock();setPremium(true);setModal(false)};
 const download=()=>{const canvas=document.createElement("canvas");canvas.width=1080;canvas.height=1350;const c=canvas.getContext("2d");c.fillStyle="#071c2f";c.fillRect(0,0,1080,1350);c.fillStyle="#e9d59d";c.font="44px Georgia";c.fillText("NAO DREAM",80,100);c.font="92px Georgia";wrap(c,card.title,80,260,900,105);c.font="38px sans-serif";c.fillStyle="#f5f0e4";c.fillText(card.culture,80,520);c.font="150px serif";c.fillText(card.emojis[0],80,735);c.font="40px Georgia";wrap(c,resonance,80,900,900,58);c.font="28px sans-serif";c.fillStyle="#b9c9cb";c.fillText("Découvert avec la noix Nao",80,1260);const a=document.createElement("a");a.download=`nao-${card.id}.png`;a.href=canvas.toDataURL();a.click()};
 return <main className="discovery"><p className="step">UN RÊVE DU MONDE A RÉPONDU</p><article className="culture-card"><CardArt card={card}/><div className="card-body"><p className="region">{card.culture} · {card.region}</p><h1>{card.title}</h1><p className="category">{card.category} · Symbole : <b>{card.symbols[0]}</b></p><p className="summary">{card.summary}</p><div className="resonance"><span>RÉSONANCE</span><p>{resonance}</p></div><p className="source">Source éditoriale : {card.sourceLabels[0]} · statut {card.editorialStatus}</p></div></article>{premium?<Premium card={card}/>:<button className="primary" onClick={()=>setModal(true)}>Ouvrir le rêve complet — 1,99 €</button>}<section className="viral"><h2>À qui cette histoire pourrait-elle parler ?</h2><div><button onClick={share}>Partager la carte</button><button onClick={share}>Copier le lien</button><button onClick={download}>Créer une image souvenir</button><button onClick={()=>go("/")}>Passer la noix</button></div><small>{shared}</small></section><p className="disclaimer">Proposition culturelle et poétique, non interprétation du rêve.</p>{modal&&<div className="modal"><div><p className="step">MODE PROTOTYPE</p><h2>Ouvrir une porte</h2><p>Aucun paiement réel ne sera effectué. Dans la version finale, cette ouverture unique coûtera 1,99 €.</p><button className="primary" onClick={open}>Simuler l’ouverture</button><button onClick={()=>setModal(false)}>Annuler</button></div></div>}</main>
}
function wrap(ctx,text,x,y,max,line){let out="";for(const word of text.split(" ")){if(ctx.measureText(out+word).width>max){ctx.fillText(out,x,y);out="";y+=line}out+=word+" ";}ctx.fillText(out,x,y)}
function Premium({card}){return <section className="premium"><p className="step">LA PORTE EST OUVERTE</p><h2>{card.title}</h2><h3>Le récit</h3><p>{card.fullStory}</p><h3>Contexte culturel</h3><p>{card.culturalContext}</p><div className="premium-grid"><div><h3>Le rêve dans cette tradition</h3><p>{card.dreamFunction}</p></div><div><h3>Symboles associés</h3><p>{card.symbols.join(" · ")}</p></div></div><blockquote>« {card.editorialQuote} »</blockquote><h3>Une question à garder</h3><p>{card.reflectionQuestion}</p><h3>Un geste créatif</h3><p>{card.creativePrompt}</p><h3>Sources</h3><ul>{card.sourceNotes.map(x=><li key={x}>{x}</li>)}</ul></section>}

function Journey({stats}){const discoveries=stats?.discoveries||[];return <main className="subpage"><p className="step">NAO-DREAM-001</p><h1>Le voyage de Nao</h1><p className="intro">Chaque passeur ajoute une étoile à son carnet de voyage. Aucune position précise n’est enregistrée.</p><div className="map"><svg viewBox="0 0 600 260" aria-label="Carte abstraite des régions"><path d="M40 90l70-50 90 35-25 80-95 30zm190-30 80-35 45 75-50 90-60-40zm160 20 95-48 80 70-55 55-80-20zm55 110 80-15 30 45-100 20z"/>{[80,180,275,400,500].slice(0,stats?.journey?.discoveredRegions?.length||5).map((x,i)=><circle key={x} cx={x} cy={70+(i%3)*55} r="9"/>)}</svg></div><div className="trip-stats"><b>{stats?.journey?.scanCount||5}<small>scans</small></b><b>{stats?.journey?.discoveredCultures?.length||5}<small>cultures</small></b><b>{stats?.journey?.discoveredRegions?.length||5}<small>régions</small></b></div><h2>Constellation des thèmes</h2><div className="theme-cloud">{Object.entries(stats?.journey?.tagScores||{voyage:3,mémoire:2,passage:2,nature:1}).map(([t,n])=><span style={{fontSize:`${.85+n*.12}rem`}} key={t}>{t}</span>)}</div><h2>Le carnet de bord</h2><div className="timeline">{discoveries.slice().reverse().map(d=>{const c=DREAM_CARDS.find(x=>x.id===d.cardId);return c&&<article key={d.id}><b>{c.emojis[0]}</b><div><time>{new Date(d.createdAt).toLocaleDateString("fr-FR")}</time><h3>{c.title}</h3><p>{c.culture} · {c.region} · {c.symbols[0]}</p></div></article>})}</div></main>}

function Atlas({stats}){const [region,setRegion]=useState("Toutes");const found=new Set(stats?.journey?.discoveredCardIds||[]);const cards=region==="Toutes"?DREAM_CARDS:DREAM_CARDS.filter(c=>c.region===region);return <main className="subpage atlas"><p className="step">COLLECTION CULTURELLE</p><h1>L’Atlas des rêves</h1><p className="intro">{found.size} cultures découvertes sur {DREAM_CARDS.length}. Les récits inconnus gardent leur mystère jusqu’à la rencontre.</p><div className="filters">{["Toutes",...new Set(DREAM_CARDS.map(c=>c.region))].map(r=><button className={r===region?"selected":""} onClick={()=>setRegion(r)} key={r}>{r}</button>)}</div><div className="atlas-grid">{cards.map(c=>{const open=found.has(c.id);return <article className={!open?"locked":""} key={c.id}>{open?<CardArt card={c}/>:<div className="silhouette">?</div>}<span>{c.region}</span><h2>{open?c.title:`Une histoire de ${c.category}`}</h2><p>{open?c.culture:`Indice : ${c.symbols[0]}`}</p><small>{open?"Découverte":"Non découverte"}</small></article>})}</div></main>}
function About(){return <main className="subpage"><p className="step">SOURCES ET DÉMARCHE</p><h1>À propos de Nao</h1><p className="intro">Nao Dream relie une inspiration personnelle à une bibliothèque éditoriale locale. Il ne prédit rien et n’interprète pas les rêves : il ouvre une fenêtre culturelle et poétique.</p><section className="text-card"><h2>Notre démarche</h2><p>Les correspondances reposent sur des tags, symboles et emojis. Les récits sont reformulés, attribués à une communauté et une région, et accompagnés de pistes bibliographiques. Le statut « draft » signale les cartes qui demandent encore une relecture spécialisée.</p><h2>Vie privée</h2><p>Pas de compte, pas de géolocalisation, pas d’IA, pas de serveur. Le voyage est enregistré uniquement dans IndexedDB sur cet appareil et peut être exporté.</p><a href="/src/content/editorialGuidelines.md">Consulter les règles éditoriales</a></section></main>}

export default function App(){const [path,go]=useRoute(),[stats,setStats]=useState(null),[input,setInput]=useState(null),[phase,setPhase]=useState("form"),[result,setResult]=useState(null),[error,setError]=useState("");const discovering=useRef(false);useEffect(()=>{ensureDemoJourney(NAO_ID).then(()=>getSnapshot(NAO_ID)).then(snapshot=>{setStats(snapshot);if(path.includes("/discovery/")){const id=path.split("/").at(-1),discovery=snapshot.discoveries.find(item=>item.id===id),contribution=snapshot.contributions.find(item=>item.id===discovery?.contributionId),card=DREAM_CARDS.find(item=>item.id===discovery?.cardId);if(discovery&&contribution&&card)setResult({discovery,contribution,card,resonance:buildResonanceText(contribution,card)})}})},[path]);const discover=async()=>{if(discovering.current)return;discovering.current=true;try{const journey=(await getSnapshot(NAO_ID)).journey;const card=selectDreamCultureCard(input,journey,DREAM_CARDS);const saved=await createContribution(NAO_ID,input,card);setResult({...saved,card,resonance:buildResonanceText(input,card)});setStats(await getSnapshot(NAO_ID));setPhase("card");go(`/nao/${NAO_ID}/discovery/${saved.discovery.id}`)}catch{discovering.current=false;setError("Nao n’a pas pu ouvrir la carte. Réessaie dans un instant.");setPhase("form")}};let page;if(path==="/")page=<Home go={go} stats={stats}/>;else if(path.includes("/journey"))page=<Journey stats={stats}/>;else if(path==="/atlas")page=<Atlas stats={stats}/>;else if(path==="/about")page=<About/>;else if(path.includes("/resonance")||path===`/nao/${NAO_ID}`)page=phase==="transition"?<Transition input={input} done={discover}/>:<><ResonanceForm onSubmit={v=>{setError("");discovering.current=false;setInput(v);setPhase("transition")}}/>{error&&<p role="alert" className="flow-error">{error}</p>}</>;else if(path.includes("/discovery")&&result)page=<Discovery {...result} go={go} onUnlock={async()=>{await unlockDiscovery(result.discovery.id);setStats(await getSnapshot(NAO_ID))}}/>;else page=<Home go={go} stats={stats}/>;return <Shell path={path} go={go}>{page}</Shell>}
