create table public.dream_journeys (
  id bigint generated by default as identity primary key,
  journey_id text not null unique,
  nao_id text not null,
  series_id text not null,
  selections jsonb not null default '{}'::jsonb,
  dream text not null default '',
  status text not null,
  received_at timestamptz,
  created_at timestamptz,
  passed_at timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.dream_journeys enable row level security;

create policy "Public clients can create dream journeys"
  on public.dream_journeys for insert to anon
  with check (true);

create policy "Public clients can update dream journeys"
  on public.dream_journeys for update to anon
  using (true)
  with check (true);
